### ISSUE TITLE
password reset adminpanel

### ISSUE THREAD

**Issue by danfield555** [afterlogic/aurora-core#1]
Hi, we have lost our admin password, how do we recover it, we have full DB access.

**Comment by nadine-belanova** [comment]
Hi,
You can change your adminpanel password by our installer. If you removed install folder earlier you can take it from WebMail package. Then open url "YOUR_WEBMAIL_INSTALLATION/install" and just click "Next" or "I Agree" buttons in most steps. On step 4 "Specify Database Settings" uncheck "Create Database Tables" checkbox. Set new adminpanel password on step 6. After all steps you can access your adminpanel with the new password. We hope this helps.

**Comment by danfield555** [comment]
Hi, thanks for your reply.  In your example you use Webmail installer, does that apply to 
afterlogic/aurora-core as well or should I use a different installer / reset procedure?

**Comment by nadine-belanova** [comment]
Hi, we supposed that you are using WebMail Lite when we answered your question. aurora-core is in the early stage of development and it's not working yet. We even didn't any public announcements about it.
