### ISSUE TITLE
v8->v9 migration issues; Was: Issue when au_min_hashes is empty

### ISSUE THREAD

**Issue by HenkPoley** [afterlogic/aurora-core#9]
I get the error:

```
# php system/bin/console -vvv migrate:eav-to-sql
File /path_to_afterlogic_webmail/data/migration-eav-to-sql/migration-progress.txt is invalid. Do you wish migrate all entities? (Y/N)Y
 0/56 [>---------------------------]   0% < 1 sec/< 1 sec 6.0 MiB
In MySql.php line 536:

  [Aurora\System\Exceptions\DbException]
  21S01
  1136
  Column count doesn't match value count at row 1 [21S01]


Exception trace:
  at /path_to_afterlogic_webmail/system/Db/Pdo/MySql.php:536
 Aurora\System\Db\Pdo\MySql->_setSqlError() at /path_to_afterlogic_webmail/system/Db/Pdo/MySql.php:337
 Aurora\System\Db\Pdo\MySql->Execute() at /path_to_afterlogic_webmail/system/Db/Storage.php:189
 Aurora\System\Db\Storage->Execute() at /path_to_afterlogic_webmail/system/Console/Commands/Migrations/EavToSqlCommand.php:81
 Aurora\System\Console\Commands\Migrations\EavToSqlCommand->migrateMinHashes() at /path_to_afterlogic_webmail/system/Console/Commands/Migrations/EavToSqlCommand.php:255
 Aurora\System\Console\Commands\Migrations\EavToSqlCommand->execute() at /path_to_afterlogic_webmail/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /path_to_afterlogic_webmail/vendor/symfony/console/Application.php:1015
 Symfony\Component\Console\Application->doRunCommand() at /path_to_afterlogic_webmail/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /path_to_afterlogic_webmail/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /path_to_afterlogic_webmail/system/bin/console:6

migrate:eav-to-sql [-w|--wipe] [-f|--migrate-file]
```

My au_min_hashes schema is:

```sql
CREATE TABLE au_min_hashes
(
    hash_id varchar(32) DEFAULT '' NOT NULL,
    hash    varchar(20) DEFAULT '' NOT NULL,
    data    text                   NULL
)
    CHARSET = utf8mb3;

CREATE INDEX au_min_hash_index
    ON au_min_hashes (hash);
```

But there is no data in there. I think that causes the issue in Aurora\System\Console\Commands\Migrations\EavToSqlCommand::migrateMinHashes() 
https://github.com/afterlogic/aurora-framework/blob/f5d3c2da93f01e48865e9d185cdeabe601373cfa/Console/Commands/Migrations/EavToSqlCommand.php#L67-L83

**Comment by HenkPoley** [comment]
I'm putting a `return true;` at the top of the function, since we are not using SelfDestructingMinHashes

But let me know if my system is missing something.

**Comment by HenkPoley** [comment]
~~From my cursory look at the code, it also seem that if you run `php system/bin/console migrate:eav-to-sql` again. Say with another future update. It will TRUNCATE (wipe!) the au_core_min_hashes table, and copy the old SelfDestructingMinHashes from au_min_hashes again.~~ <-- This is irrelevant, you should only run it once.

🤔

**Comment by afterlogic-support** [comment]
I'll check with the developers and see if they have any ideas what could be causing this, but first I'd like to clarify what product and version you're upgrading from and to. Migrating EAV to SQL is only needed if you upgrade from v8 to v9, and it's only done once, so i'm not certain where future updates come into play.

**Comment by HenkPoley** [comment]
Ah, I see. I thought it was a normal migration step. So the 'again' part is irrelevant.

Still, the data migration breaks on my acceptance system.

**Comment by afterlogic-support** [comment]
And what about this part?

> what product and version you're upgrading from and to

**Comment by HenkPoley** [comment]
Afterlogic Webmail Pro 8.5.2 to 9.3.1 (I am aware there are probably updates to 9.x; e.g. 9.5.0.build15-build-a3)

**Comment by HenkPoley** [comment]
I've update the original commandline result with one that gave the error that pointed me to EavToSqlCommand::migrateMinHashes()

**Comment by afterlogic-support** [comment]
Thank you. Developers have confirmed the issue and have provided a fix for it. You can use [the attached patch](https://github.com/afterlogic/aurora-framework/files/8861940/0001-fixed-Issue-when-min_hashes-table-is-empty.zip), or modify the code manually - the following code in `migrateMinHashes` function, `system/Console/Commands/Migrations/EavToSqlCommand.php` file:

```php
$sql = "TRUNCATE `" . $this->oP8Settings->DBPrefix . "core_min_hashes`;";
$oConnection->execute($sql);
$sql = "INSERT INTO " . $this->oP8Settings->DBPrefix . "core_min_hashes (`HashId`, `UserId`,`Hash`, `Data`, `ExpireDate`)
SELECT *
FROM " . $this->oP8Settings->DBPrefix . "min_hashes;";
$oConnection->execute($sql);
return true;
```

needs to be replaced with:

```php
$sql = "TRUNCATE `" . $this->oP8Settings->DBPrefix . "core_min_hashes`;";
$oConnection->execute($sql);
$sql = "SELECT * FROM " . $this->oP8Settings->DBPrefix . "min_hashes;";
$oConnection->execute($sql);
if ($oConnection->ResultCount() > 0) {
	$sql = "INSERT INTO " . $this->oP8Settings->DBPrefix . "core_min_hashes (`HashId`, `UserId`,`Hash`, `Data`, `ExpireDate`)
	SELECT *
	FROM " . $this->oP8Settings->DBPrefix . "min_hashes;";
	$oConnection->execute($sql);
}
return true;
```

Please let us know if this helps you. Thanks!

P.S. And yes, we've just released WebMail Pro v9.5 :)

**Comment by HenkPoley** [comment]
With the patch, the MinHashes migration no longer gives an error on our acceptance system. That said, there is no data in that table.

I am not sure how a table with 3 columns (hash_id, hash, data) is supposed to go into that 5 column (HashId, UserId, Hash, Data, Expired) insert though.

I think it needs some kind of JOIN to fetch those missing UserId, Expired from, and to move HashId to hash_id.

**Comment by afterlogic-support** [comment]
> I am not sure how a table with 3 columns (hash_id, hash, data) is supposed to go into that 5 column (HashId, UserId, Hash, Data, Expired) insert though.

Did you actually run `php system/bin/console migrate` prior to `php system/bin/console migrate:eav-to-sql`? That's where new columns are added which are required by v9 and weren't there in v8.

**Comment by HenkPoley** [comment]
Yes, I did run run `php system/bin/console migrate`. I'll check which migration adds these columns.

**Comment by HenkPoley** [comment]
I'm seeing a [migration for (au_)core_min_hashes](https://github.com/afterlogic/aurora-module-min/blob/5bece610cc3fab5924f12d0bd66d480c8d7c54d5/Migrations/2021_06_29_083240_create_min_hashes_table.php) (to create the table), but not (au_)min_hashes

**Comment by HenkPoley** [comment]
Ah, it used to do a rename. But not anymore.

https://github.com/afterlogic/aurora-module-min/commit/118bd7ce7460fa7a5741125ee8cb47e502177f75

I don't think what it says would work, since it didn't have a user_id to begin with, for example.

**Comment by HenkPoley** [comment]
I think this is the old-style 'migration' in the Afterlogic WebMail Pro version (8.5.2) that I came from. That should have added user_id and expire_date columns: https://github.com/afterlogic/aurora-module-min/blob/6dd53cfb374f36658e3cd1657353fb45bcbb1cc1/Manager.php#L201-L227

But I am not sure _when_ this would have been executed.

**Comment by afterlogic-support** [comment]
I've forwarded this information to the developers, will let you know once there's a response from them.

**Comment by afterlogic-support** [comment]
I think we know why the issue has occured. [Upgrading instructions](https://afterlogic.com/docs/webmail-pro/installation/upgrading-instructions#upgrading-from-v8) include the following part:

> **NB:** The migration was only tested with the latest v8 release, so be sure you're on the latest 8.8 version, if not - upgrade it first, per the above guidelines. You can download the latest v8 at: https://afterlogic.com/download/webmail-pro-8

Thus, you need to upgrade your WebMail Pro install to the latest v8 available, and then proceed with upgrading to v9.

**Comment by HenkPoley** [comment]
Hmm, how sure are you that the Afterlogic Webmail Pro 8.8 migrations do not have the same "you have to execute it once and only once, or it will overwrite new data with old data" property of Webmail Pro 9.x ? E.g. if I already start at some lower Webmail Pro 8.x (e.g. 8.5.2).

**Comment by afterlogic-support** [comment]
As long as we're speaking of running "Create/update tables" tool within the same major version 8, no data are deleted or overwritten, all it does is creating new tables and columns where necessary.

**Comment by HenkPoley** [comment]
Ah the _"Create/update tables" tool_ is: 4. Log into /adminpanel/ as superadmin, navigate to Database Settings screen, and click "Create/Update tables" and "Update configuration" buttons.

Src: https://afterlogic.com/docs/webmail-pro-8/installation/upgrading-instructions

We _very rarely_ use the admin panel. But we'll get in there.

Just to be clear, I should absolutely NOT click _"Update configuration"_ while in there ? (Edit: probably safe as well)

**Comment by afterlogic-support** [comment]
> Just to be clear, I should absolutely NOT click "Update configuration" while in there ?

That only affect module configuration files and isn't related to database update. And it's best to run that tool, yes.

**Comment by HenkPoley** [comment]
Since this ticket is mainly a 'migrations of WebMail Pro 8 needs to be run'.

I think I would like it if here: https://afterlogic.com/docs/webmail-pro-8/installation/upgrading-instructions

.. these things were documented:

* The `data/` directory needs to be writable by your webserver. E.g. where it says you need to keep or copy the `data/` directory. Else you will get an opaque error message that your system is not configured (API responds with 112, SystemNotConfigured).
* At point 4 'Log into `/adminpanel/` as superadmin': change it so it is obvious you just need to login _at the normal login page_. Since <webmail domain>/adminpanel/ will give a standard "404 Not Found" error message from your webserver (if you are not logged in). Leading you to searching how to enable the page.
* Explain that one can refer to a `data/` directory outside of the document root with an [`inc_settings_path.php`](https://afterlogic.com/docs/webmail-pro/security/protecting-data-directory) file (link to [the documentation](https://afterlogic.com/docs/webmail-pro/security/protecting-data-directory)). Even just mentioning `inc_settings_path.php` would help a lot. There is already a link, but it's more phrased like an afterthought about tightening security some more.
* Maybe create a `inc_settings_path.example.php` (in git / the zip) with some comments in there that will help you find it when you grep / use IDE search. Currently I have the 2 lines about this from the 'protecting data directory' documentation quoted in there and the keywords: `../data`, `PATH_SEPARATOR`, `DIRECTORY_SEPARATOR`, `webroot`, `DocumentRoot`
* Possibly also link to ['How to reset [super]admin password'](https://afterlogic.com/docs/webmail-pro-8/frequently-asked-questions/how-to-reset-admin-password) (the page doesn't mention "superadmin", btw).

Since I simply extracted the AfterLogic WebMail Pro 8.8.6 zip to a copy of my working setup, and pointed a new Vhost to it, none if it worked as I expected, without figuring the above out. I wasn't the one who originally set things up. And even then, it was a while ago.

**Comment by afterlogic-support** [comment]
Thank you, we'll have this considered of course. While the upgrading instructions are about upgrading within current version 9, as mentioned in the first paragraph:
> Please use the following instructions to upgrade from previous v9.* of WebMail Pro to the latest version of WebMail Pro.

and the `/adminpanel/` part is actually correct in v9, dealing with v8 is a separate "Upgrading from v8" section down the page - I do agree that, if you're upgrading within v8, the section could use the improvements. Thanks again!

**Comment by HenkPoley** [comment]
- In my local development environment it worked.
- In our acceptance environment it worked.
- But for some reason things are failing / missing on our production system. 

Thing we noticed, we can't log in (Api: 112; only ApiException in logs). So we rolled back.

What I notice in the 'broken' database that I kept, is that there are no tuples in au_mail_servers. Which in v9 should contain for example IncomingServer. If this is missing, that seems plausible as a reason that you cannot login.

Grepping through the code (even a fresh 9.5.2 zip) it is not entirely clear to me where this IncomingServer data migration should have happened? There are no errors in data/migration-eav-to-sql/ (only 0 byte .txt files). There were also no errors when running the Eloquent migrations to create the v9 tables.

In principle these server configs are easy to fix. But, how do I figure out more things are missing, before I put things live?

**Comment by afterlogic-support** [comment]
> Thing we noticed, we can't log in (Api: 112; only ApiException in logs). So we rolled back.

By default, API exceptions stacktrace isn't included in the logs as it may contain sensitive data such as passwords. Set "LogStackTrace" to true in `data/settings/config.json` configuration file, that way complete troubleshooting information will become available.

> * In my local development environment it worked.
> * In our acceptance environment it worked.
> * But for some reason things are failing / missing on our production system.

Is there a chance PHP and database configuration are different on your production system compared to test environment? My guesses are, it may be running MySQL prior to 5.7.8 (MariaDB older than 10.2.7) or maybe something's about PHP extension missing, v9 is more demanding in that area compared to v8 (see [System requirements](https://afterlogic.com/docs/webmail-pro/system-requirements)).

I'd suggest to try running a blank install of WebMail Pro v9 on the production system, and see if it works. If it does, then it's probably the migration. 

> Grepping through the code (even a fresh 9.5.2 zip) it is not entirely clear to me where this IncomingServer data migration should have happened?

It's done for all the objects similarly, `system/Console/Commands/Migrations/EavToSqlCommandphp` script does the job and only a few special cases are handled individually. There is no separate processing of mailserver objects as the model didn't change, just the storage representation.

**Comment by HenkPoley** [comment]
🤔 Yes. We had to upgrade MariaDB on acceptance to get the json column type working. But prod runs MariaDB 10.4.24, which is new enough.

Thanks for the help. I'll check LogStackTrace and EavToSqlCommand (again).

**Comment by HenkPoley** [comment]
Figured out one thing. [On our production machine] It _silently_ runs out of memory in the while GetNextRecord() loop in EavToSqlCommand::execute(), either during fetching of more data, or when it appends $oRow to $entities array.

The while loop in question that silently ran out of memory: https://github.com/afterlogic/aurora-framework/blob/6be51446317477f22f635415a7de9248313f8ceb/Console/Commands/Migrations/EavToSqlCommand.php#L245-L251

Tomorrow is another day for debugging 😅.

**Comment by HenkPoley** [comment]
~~_This might be another 'please migrate to latest 8.x version first'. So let me check that._~~
_Though I don't understand how this call could work_

_Edit: Ran the 8.8.6 migrations first. Still hitting the same problematic code path_

It crashes while migrating a user on the `->updateAccount()` call inside \Aurora\Modules\Mail\Classes\Account::getPassword(): 

https://github.com/afterlogic/aurora-module-mail/blob/c1237cb9da9b181ca90408dda60d15770fbf1b91/Classes/Account.php#L61

Due to a type check in \Aurora\Modules\Mail\Managers\Accounts\Manager::updateAccount()

https://github.com/afterlogic/aurora-module-mail/blob/2a5a76ee6c341229ca7044b232e9aada527c7ad2/Managers/Accounts/Manager.php#L234

Aurora\Modules\Mail\Classes\Account is not Aurora\Modules\Mail\Models\MailAccount 

```
Fatal error: Uncaught TypeError: Argument 1 passed to Aurora\Modules\Mail\Managers\Accounts\Manager::updateAccount() must be an instance of Aurora\Modules\Mail\Models\MailAccount, object given, called in /path/to/afterlogic/webmail/pro/webroot/modules/Mail/Classes/Account.php on line 74 and defined in /path/to/afterlogic/webmail/pro/webroot/modules/Mail/Managers/Accounts/Manager.php:234
Stack trace:
#0 /path/to/afterlogic/webmail/pro/webroot/modules/Mail/Classes/Account.php(74): Aurora\Modules\Mail\Managers\Accounts\Manager->updateAccount(Object(Aurora\Modules\Mail\Classes\Account))
#1 /path/to/afterlogic/webmail/pro/webroot/system/Console/Commands/Migrations/EavToSqlCommand.php(325): Aurora\Modules\Mail\Classes\Account->getPassword()
#2 /path/to/afterlogic/webmail/pro/webroot/system/Console/Commands/Migrations/EavToSqlCommand.php(260): Aurora\System\Console\Commands\Migrations\EavToSqlCommand->migrate(Resource id #382, Resource id #383, Array, Array, Object(Symfony\Component\Consol in /path/to/afterlogic/webmail/pro/webroot/modules/Mail/Managers/Accounts/Manager.php on line 234
```

```
# php --version
PHP 7.4.29 (cli) (built: Apr 12 2022 10:55:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.29, Copyright (c), by Zend Technologies
```

**Comment by HenkPoley** [comment]
So, it looks like the refactoring of Aurora\Modules\Mail\Classes\Account to Aurora\Modules\Mail\Models\MailAccount in https://github.com/afterlogic/aurora-module-mail/commit/07a160e3793d72154e358b2ab06475caf283269c#r78472499 is not finished.

**Comment by afterlogic-support** [comment]
Thank you. Developers have just corrected the issue:
https://github.com/afterlogic/aurora-module-mail/commit/3f35574e7a158c72a01aa3e41d2f49dd76a94495

Hope it helps.

**Comment by HenkPoley** [comment]
For customer's sanity, maybe also put this at the top of EavToSqlCommand->execute():

```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

And consider renaming migrate:eav-to-sql something like migrate:eav-to-sql-real, and making a new command 'migrate:eav-to-sql' that starts a new php process with appropriate memory limits. Plus some sanity checks before and after.

E.g. if the max. entity_id (or max count?) is higher than what the migration log says. Tell the user that something didn't finish.

**Comment by HenkPoley** [comment]
Oh, and yes the patch works. Or at least no errors at the point where it would silently fail.
